# workflowの名前
name: Sample actions

# トリガーの設定
on:
  push:
    branches: master # mainブランチの場合はmainに変更

jobs:
  build:
    runs-on: ubuntu-latest # 実行環境の設定

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world! # Hello, world!と出力する
